import type { LayoutConfig } from "../../../domain/document";
import type { ComponentChildren } from "preact";

type UpdateConfig = <Key extends keyof LayoutConfig>(key: Key, value: LayoutConfig[Key]) => void;
type Density = Exclude<LayoutConfig["density"], "custom">;
type ReadingSetting = "bodyFontSize" | "bodyLineHeight" | "blockGap" | "headingH2BeforeSpacing" | "headingH3BeforeSpacing";

const Range = ({ label, value, children }: { label: string; value: string; children: ComponentChildren }) => <label class="range-label">{label} <output>{value}</output>{children}</label>;

export function LayoutSettings({ config, onConfigChange, onReadingConfigChange, onApplyDensity }: { config: LayoutConfig; onConfigChange: UpdateConfig; onReadingConfigChange: (key: ReadingSetting, value: number) => void; onApplyDensity: (density: Density) => void }) {
  return <>
    <section class="settings-category-content"><h3>排版</h3><h4>整体密度</h4><div class="density-choices density-preset-choices">{(["relaxed", "balanced", "compact"] as const).map((density) => <button key={density} class={config.density === density ? "selected" : ""} onClick={() => onApplyDensity(density)}>{{ relaxed: "舒展", balanced: "技术平衡", compact: "紧凑" }[density]}</button>)}</div><p class="field-help">预设会同步调整正文字号、行距、标题留白与代码字号；表格、公式和图片保持单独控制。</p>{config.density === "custom" && <div class="density-custom-state"><span>已按下方参数微调整体密度。</span><button type="button" class="secondary-button" onClick={() => onApplyDensity("balanced")}>恢复技术平衡</button></div>}<h4>正文</h4><div class="setting-control-grid"><Range label="正文字号" value={`${config.bodyFontSize}px`}><input type="range" min="26" max="34" value={config.bodyFontSize} onInput={(e) => onReadingConfigChange("bodyFontSize", Number(e.currentTarget.value))} /></Range><Range label="正文行距" value={config.bodyLineHeight.toFixed(2)}><input type="range" min="1.45" max="1.78" step="0.01" value={config.bodyLineHeight} onInput={(e) => onReadingConfigChange("bodyLineHeight", Number(e.currentTarget.value))} /></Range><Range label="块间距" value={`${config.blockGap}px`}><input type="range" min="0" max="32" step="2" value={config.blockGap} onInput={(e) => onReadingConfigChange("blockGap", Number(e.currentTarget.value))} /></Range></div></section>
    <section class="settings-category-content"><h3>标题</h3><p class="field-help">标题留白只在标题不位于卡片首块时生效，并会参与分页计算。</p><div class="setting-control-grid"><Range label="H2 章节前留白" value={`${config.headingH2BeforeSpacing}px`}><input type="range" min="0" max="72" step="4" value={config.headingH2BeforeSpacing} onInput={(e) => onReadingConfigChange("headingH2BeforeSpacing", Number(e.currentTarget.value))} /></Range><Range label="H3 小节前留白" value={`${config.headingH3BeforeSpacing}px`}><input type="range" min="0" max="40" step="2" value={config.headingH3BeforeSpacing} onInput={(e) => onReadingConfigChange("headingH3BeforeSpacing", Number(e.currentTarget.value))} /></Range></div><h4>标题分页</h4><p class="field-help">H2 会优先携带短引言后的实质内容，或首个 H3 与其首段；数值表示标题顶部进入页尾多少比例后自动转到下一页。</p><div class="setting-control-grid"><Range label="H2 页尾安全区" value={`${config.headingH2TailPercent}%`}><input type="range" min="10" max="35" value={config.headingH2TailPercent} onInput={(e) => onConfigChange("headingH2TailPercent", Number(e.currentTarget.value))} /></Range><Range label="H3 页尾安全区" value={`${config.headingH3TailPercent}%`}><input type="range" min="4" max="22" value={config.headingH3TailPercent} onInput={(e) => onConfigChange("headingH3TailPercent", Number(e.currentTarget.value))} /></Range><Range label="H4 页尾安全区" value={`${config.headingH4TailPercent}%`}><input type="range" min="0" max="14" value={config.headingH4TailPercent} onInput={(e) => onConfigChange("headingH4TailPercent", Number(e.currentTarget.value))} /></Range></div></section>
  </>;
}
